Feat/home page illustrations link
veganhacktivists/wildanimalsuffering pull request #18
Opened 2022-10-17 12:20 UTC by trybick

- Decrease size of hamburger menu
- Add Link for "Illustrations by Kate Rodman"

2022-10-17 12:26 UTC, trybick commented
@stephan281094 Forgot to make this part mobile friendly. Will work on that now and then push updates.

2022-10-17 14:44 UTC, stephan281094 requested changes
Nice work, a few comments here and there, but keep it up!

2022-10-17 14:44 UTC, stephan281094 commented on src/components/header/index.js
> +        <div className="text-4xl">En</div>
I think we can remove this for now. The first launch of this website will likely be without translations.

2022-10-17 14:44 UTC, stephan281094 commented on src/components/header/index.js
> +        <div className="bg-search bg-contain bg-no-repeat bg-center h-[26px] aspect-square color-[#fff] ml-12" />
`color-[value]` is not a valid TailwindCSS class. I think you might be looking for `text-white` in this case

2022-10-17 14:44 UTC, stephan281094 commented on src/components/header/index.js
> +    <div className="fixed top-0 left-0 z-40 p-20 shrink-0 flex items-center">
Is setting the z-index necessary here? With its position set to `fixed`, it should already create a new stacking context.

2022-10-17 14:44 UTC, stephan281094 commented on src/components/header/index.js
> +        rel="noopener noreferrer"
This is a nice touch! Although I think `noreferrer` already encapsulates the `noopener` functionality.

2022-10-17 14:44 UTC, stephan281094 commented on src/components/navigation-menu/index.js
> +        <div className="h-[2.5px] w-[30px] bg-white md:bg-black rounded-full"></div>
Instead of divs, I think it makes more sense to use an SVG for displaying the hamburger icon.

2022-10-17 14:44 UTC, stephan281094 commented on src/utils/screen.js
> +  return window.innerWidth < parseInt(fullConfig.theme.screens.md);
This implementation might not always work. For instance, when resizing the browser, or going from portrait to landscape. For simple markup I think it makes more sense to have two different divs like so (if both implementations differ a lot):
```html
<div class="md:hidden">
  <!-- mobile implementation -->
</div>
<div class="hidden md:flex">
  <!-- desktop implementation -->
</div>
```

2022-10-17 14:44 UTC, stephan281094 commented on tailwind.config.js
> +        darkGray: "#3F3E3E",
I'd like to suggest the following, where darkGray is part of the gray scale. Or we could maybe replace 700 with "dark" to give us the `text-gray-dark` class.
```suggestion
        gray: {
          700: "#3f3e3e",
        },
```

2022-10-17 14:44 UTC, stephan281094 commented on tailwind.config.js
> +        search: 'url("../assets/icons/search.png")',
Can't we get an SVG version of the search icon and use it directly? This does not seem like a good candidate for a background image. The icon also seems a bit gray, rather than white.

2022-10-17 14:44 UTC, stephan281094 commented on src/components/header/index.js
> +        <div className="bg-search bg-contain bg-no-repeat bg-center h-[26px] aspect-square color-[#fff] ml-12" />
Btw, it's a bit odd that on mobile we use the white color, while on desktop we use the black color. We should discuss this with the designers.

2022-10-17 16:01 UTC, trybick commented on src/components/why-it-matters/index.js
> +        />
This is the site logo that I added in a previous PR but here I am replacing the background image PNG with an SVG image.  Note the mobile logo, on the line below, still uses the background image. I tried replacing it with the white logo, but had trouble getting the white logo to appear. Also note there are a 2-3 other places using the background image logo.

2022-10-17 16:02 UTC, trybick commented on tailwind.config.js
> +        darkGray: "#3F3E3E",
Great idea!

2022-10-17 16:03 UTC, trybick commented
@stephan281094 Thank you for the feedback! Let me know how the updates look

2022-10-18 09:44 UTC, stephan281094 approved these changes

2022-10-18 09:45 UTC, merged